version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=evently
      - POSTGRES_PASSWORD=evently
      - POSTGRES_DB=evently
    ports:
      - "5432:5432"

  api:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data:
